name: ooi-test
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - requests
  - xarray
  - netcdf4
  - pandas
  - numpy
  - matplotlib
  - bokeh
  - cmocean
  - obspy
  - pip:
    - pycamhd