name: mapping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - basemap
  - bokeh
  - cartopy
  - earthsim
  - fiona
  - folium
  - geopandas
  - geoviews
  - gridgeo
  - ipyleaflet
  - jupyter
  - jupyter_contrib_nbextensions
  - palettable
  - rasterio
  - rise
  - shapely
  - xarray
  - xlrd
